### ISSUE TITLE
Exception Deploying Stack using ArgoCD v1.8.7 and Kustomize v4.0.5 custom-tool

### ISSUE THREAD

**Issue by rawc0der** [argoflow/argoflow#38]
Hello everyone,

I have encountered the following error for the `Dex Istio` Application resource after trying to deploy using ArgoCD `version 1.2`.

```
rpc error: code = Unknown desc = Manifest generation error (cached): 
`kustomize build /tmp/https:__github.com_argoflow_argoflow/kubeflow/common/dex-istio --enable_alpha_plugins` failed exit status 1: 
Error: accumulating resources: accumulateFile "accumulating resources from 'github.com/kubeflow/manifests/common/dex/overlays/istio': evalsymlink failure on '/tmp/https:__github.com_argoflow_argoflow/kubeflow/common/dex-istio/github.com/kubeflow/manifests/common/dex/overlays/istio' : 
lstat /tmp/https:__github.com_argoflow_argoflow/kubeflow/common/dex-istio/github.com: no such file or directory", accumulateDirector: "recursed accumulation of path '/tmp/kustomize-166861452/repo': accumulating resources: accumulateFile \"accumulating resources from '../../base': 
evalsymlink failure on '/tmp/base' : lstat /tmp/base: no such file or directory\", loader.New \"error loading ../../base with git: url lacks host: ../../base, dir: evalsymlink failure on '/tmp/base' : lstat /tmp/base: no such file or directory, get: invalid source string: ../../base\""
```

The `kustomize 4.0.5` is not present in my current Argo Server, could this be the cause for the error? 
All the other components have started successfully, so my hunch is that `Kustomize 4.0.5` is definitely a dependency for building this stack.

Any ideas?  
Thanks!

**Comment by DavidSpek** [comment]
I'm not sure what the version of Kustomize is that shipped with Argo CD v1.2, but to avoid problems you might want to add kustomize v4.0.5 as a custom tool to your Argo CD deployment. Here is the kustomize patch I use for adding this custom version of Kustomize to Argo CD. 
https://github.com/argoflow/argoflow/blob/master/argocd/add-custom-kustomize.yaml

**Comment by rawc0der** [comment]
Thanks @DavidSpek for the reply. 
I updated the Argo kustomize extension, but going through some hard time understanding why, it's not picking up the second kustomize version (BTW, the `ArgoCD` version used is actually `v1.8`).
Getting this `kustomize version v4.0.5 is not registered` error, so probably argocd v1.8 is not supporting it.. still getting my head around the issue, as I'm retrofitting the whole repository into a larger setup.

**Comment by DavidSpek** [comment]
After changing the deployment for the repo-servers, did you kill all it's pods? Also, if you exec into the pods, does the kustomize executable exist there?

**Comment by rawc0der** [comment]
yes, I redeployed Argo, wondering if the patch needs to be done on both the `argocd-server`  and `argocd-repo-server` Deployments.

**Comment by rawc0der** [comment]
The configmap has following setup (after couple of iterations of course):
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  admin.enabled: "true"
  kustomize.buildOptions: "--enable_alpha_plugins"
  kustomize.path.v4.0.5: /usr/local/bin/kustomize_4_0_5
  kustomize.buildOptions.v4.0.5: ""
```
If you're also wondering, yes the container has the tool under `/usr/local/bin/kustomize_4_0_5` path.

**Comment by rawc0der** [comment]
Ok, so upgraded from previous ref `v1.8.7 to v2.0.1` solved the issue.. thanks again!

**Comment by DavidSpek** [comment]
Strange, you'd think it would work with any version of Argo CD since the kustomize is being added as a custom tool. But good to know you got is solved.

**Comment by paravatha** [comment]
@rawc0der @DavidSpek 
I am getting the same error 

`ComparisonError: kustomize version v4.0.5 is not registered (retried 5 times).`

**Comment by DavidSpek** [comment]
@paravatha Did you deploy Argo CD with the included manifests?

**Comment by paravatha** [comment]
@DavidSpek I followed these instructions 
https://github.com/argoflow/argoflow#deploy-metallb 
I used GKE 1.18.16-gke.502, Argo CD V2.0.1 and Kustomize 4.05

**Comment by DavidSpek** [comment]
@paravatha I don't think you should be deploying MetalLB on GKE. Can you check if the `/custom-tools/kustomize_4_0_5` binary exists in the `argocd-repo-server` pods?

**Comment by paravatha** [comment]
> @paravatha I don't think you should be deploying MetalLB on GKE. Can you check if the `/custom-tools/kustomize_4_0_5` binary exists in the `argocd-repo-server` pods?

I didn't realize this will not work on GKE, I will try with other installation options. 
Feel free to close it!
